config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.contrib.staticfiles.views import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include('profiles.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('accounts/profile/add', views.profile_post_add, name='profile_post_add'),
    path('accounts/register/done', views.RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', views.RegisterUserView.as_view(), name='register'),
    path('accounts/profile/change/', views.ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/alluser/', views.alluser, name='alluser'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/main_for_all/<int:pk>/', views.main_for_all, name='main_for_all'),
    path('accounts/logout/', views.MoonLogoutView.as_view(), name='logout'),
    path('accounts/login/', views.MoonLoginView.as_view(), name='login'),
    path('post/<str:author>/<int:post_pk>/', views.detail, name='detail'),
    path('', views.home, name='home'),
]

profiles/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Profile(AbstractUser):
    GENDER = (
        ('male', 'male'),
        ('female', 'female')
    )
    login_time = models.DateTimeField(null=True)
    phone = models.CharField(max_length=14, verbose_name='Номер')
    avatar = models.ImageField(upload_to='avatar/', verbose_name='Аватар', blank=True, null=True)
    bio = models.TextField(blank=True, null=True, verbose_name='О себе')
    birthday = models.DateField(blank=True, null=True, verbose_name='День рождения')
    gender = models.CharField(max_length=6, choices=GENDER, default='Пол')


class Post(models.Model):
    author = models.ForeignKey(Profile, related_name='post', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='articles/', verbose_name='Фото')
    text = models.TextField(verbose_name='Текст под  постом')
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='Опубликован')


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')
    author = models.ForeignKey(Profile, related_name='coment', on_delete=models.CASCADE)
    content = models.TextField(verbose_name='Содержание')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликован')

profiles/forms.py
from django import forms
from django.forms import DateTimeField
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from .models import Profile, Post, Comment
from captcha.fields import CaptchaField


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Введите тот же самый пароль еще раз для проверки')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        user.is_activated = True
        if commit:
            user.save()
        return user

    class Meta:
        model = Profile
        fields = (
            'username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'phone', 'gender', 'birthday',
            'bio',
            'avatar')


class ChangeUserInfoForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('username', 'email', 'first_name', 'last_name', 'phone', 'bio', 'avatar')


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}


class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        widgets = {
            'author': forms.HiddenInput,
            'post': forms.HiddenInput
        }

profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.views import LoginView, LogoutView
from .models import Profile, Post, Comment
from django.urls import reverse_lazy
from .forms import RegisterUserForm, ChangeUserInfoForm, PostForm, UserCommentForm
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages


def home(request):
    all_posts = Post.objects.all()
    return render(request, 'layout/basic.html', {'all_posts': all_posts})


class MoonLoginView(LoginView):
    template_name = 'main/login.html'


class RegisterUserView(CreateView):
    template_name = 'main/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


@login_required
def profile(request):
    posts = Post.objects.filter(author=request.user.pk)
    return render(request, 'main/profile.html', {'posts': posts})


class MoonLogoutView(LogoutView, LoginRequiredMixin):
    template_name = 'main/logout.html'


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Profile
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


@login_required
def profile_post_add(request):
    erorr = ''
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('main:profile')
        else:
            erorr = 'Не верно введеные даные'
    else:
        form = PostForm(initial={'author': request.user.pk})
    context = {'form': form, 'erorr': erorr}
    return render(request, 'main/profile_post_add.html', context)


def alluser(request):
    search_query = request.GET.get('search', '')
    if search_query:
        all_user = Profile.objects.filter(username=search_query)
    else:
        all_user = Profile.objects.all()
    return render(request, 'main/alluser.html', {'all_user': all_user})


def detail(request, post_pk, author):
    authorr = Profile.objects.get(username=author)
    post = Post.objects.filter(id=post_pk)
    comments = Comment.objects.filter(post_id=post_pk)
    erorr = ''
    if request.method == 'POST':
        form = UserCommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')
        else:
            erorr = 'Не верно введеные даные'
    else:
        form = UserCommentForm(initial={'post': post_pk, 'author': request.user.pk})
    context = {'form': form, 'erorr': erorr, 'post': post, 'authorr': authorr, 'comments': comments}
    return render(request, 'main/detail.html', context)


def main_for_all(request, pk):
    userr = Profile.objects.filter(id=pk)
    posts = Post.objects.filter(author_id=pk)
    return render(request, 'main/main_for_all.html', {'posts': posts,'userr': userr})

templates/layout/basic.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

       <title>Document</title>
    </head>
<body style = "height: 5000px;" style="background-color:#ff6347;">
<nav class="navbar sticky navbar-expand-sm  navbar-dark bg-dark">
  <div class="container">   <a class="navbar-brand" >
      moonst
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false">
        <spam class="navbar-toggler-icon"></spam>
      </button>
      <div class="collapse navbar-collapse" id="navbarContent">
        <ul class = "navbar-nav mr-auto mb-2">
          <li class ="nav-item">
            <a href="{% url 'main:alluser' %}" class="nav-link">Главная</a>
          </li>
        </ul>
         <ul class = "navbar-nav mr-auto mb-2">
          <li class ="nav-item">
            <a href="/" class="nav-link">Посты</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
        <ul class = "navbar-nav mr-auto mb-2">
          <li class ="nav-item">
            <a href="{% url 'main:profile' %}" class="nav-link">Мой профиль</a>
          </li>
        </ul>
      </div>
          <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Имя пользователя" aria-label="Search">
        <button class="btn btn-outline-success me-md-2" type="submit">Найти</button>
      </form>
         <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <a href="{% url 'main:logout' %}" class="btn btn-outline-danger " role="button" >Выход</a>
          </ul>
           </div>
         
              {% else %} 
         <ul class = "navbar-nav mr-auto mb-2">
          <li class ="nav-item">
            <a href="{% url 'main:login' %}" class="nav-link">Войти</a>
          </li>
        </ul>

        </div>
  <form class="d-flex" action="{% url 'main:alluser'%}">
        <input class="form-control me-2" type="search" placeholder="Имя пользователя" aria-label="Search" name="search">
        <button class="btn btn-outline-success" type="submit">Найти</button>
      </form>
     {%endif%}
    </div>
</nav>
<main>
{%block content%}
    {%for tr in  all_posts%}
    <div class="container my-5">
      <div class="row">
        <div class = "col-md-8">
          <a href="{% url 'main:detail' post_pk=tr.pk author=tr.author%}">
          <img class="w-50" src="{{tr.image.url}}">
        </a>
        </div>
        <div class = "col-md-4 text-left">
           <h2>{{tr.author}}</h2>
           {%if tr.text%}
           <p>{{tr.text}}</p>
           {% endif %}
        </div>
    </div>
     {%endfor%} 
{% endblock %}
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

templates/main/alluser.html
{% extends "layout/basic.html" %}
{%block content%}
   {%for tr in  all_user%}
    {% if tr.avatar%}
    <div class="container my-5">
      <div class="row">
        <div class = "col-md-8">
          <a href="{% url 'main:main_for_all' pk=tr.pk %}">
          <img class="w-50" src="{{tr.avatar.url}}">
        </a>
        </div>
        <div class = "col-md-4 text-left">
           <h2>{{tr.username}}</h2>
           {% if tr.bio%}
           <p>О себе:{{tr.bio}}</p>
           {% endif %}
        </div>
    </div>
    {% endif %}
     {%endfor%}
{% endblock %}

templates/main/change_user_info.html
{% extends "layout/basic.html" %}
{% load bootstrap5 %}
{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
{% csrf_token %}
{% bootstrap_form form layout='horizontal' %}
{% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

templates/main/detail.html
{% extends "layout/basic.html" %}
{% load bootstrap5 %}
{%block content%}
{%for vv in post%}
<div class="container my-5">
      <div class="row justify-content-md-center">
        <div class = "col-md-8">
          <img class="w-100" src="{{vv.image.url}}">
      </div>
</div>
<h3>Подпись автора({{vv.author}}):{{vv.text}}</h3>
{%endfor%}
{% if comments%}
Коментарии:
{%for ff in comments%}
 <h5>{{ff.author}}:{{ff.content}}</h5>

{%endfor%}
 {% endif %}
{% if user.is_authenticated %}
    <b2>Добавить свой коментарий</b2>
<form method="post" enctype="multipart/form-data" >
  {% csrf_token %}
  {{form.as_p}}
  {% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% endif %}

{% endblock %}

templates/main/login.html
{% extends "layout/basic.html" %}
{% load bootstrap5 %}
{%block content%}
  {% if user.is_authenticated %}
<р>Вы уже выполнили вход.</р>
{% else %}
<form method="post">
{% csrf_token %}
{% bootstrap_form form layout='horizontal' %}
<input type="hidden" name="next" value="{{ next }}">
{% buttons submit='Войти' %}{% endbuttons %}

</form>
<a href="{% url 'main:register' %}" class="btn btn-outline-success  me-md-2" role="button">Peгистрация</a>
{% endif %}

{% endblock %}

templates/main/logout.html
{% extends "layout/basic.html" %}
{%block content%}
  <h1>Вы вишли из профиля</h1>
{% endblock %}

templates/main/main_for_all.html
{% extends "layout/basic.html" %}
{%block content%}
{%for use in  userr%}
    <div class="container my-3">
      <div class="row">
         <div class = "col-md-4 text-left">
           <h2>{{use.username}}</h2>
            <p>Телефон:{{use.phone}}</p>
           <p>День рождения:{{use.bithrday}}</p>
           <p>О себе:{{use.bio}}</p>
        </div>
        <div class = "col-md-6">
          <a >
          <img class="w-100" src="{{use.avatar.url}}">
        </a>
        </div>
      </div>
      {%endfor%}
       {%for tr in  posts%}
    <div class="container my-5">
      <div class="row">
        <div class = "col-md-8">
          <a href="{% url 'main:detail' post_pk=tr.id author=tr.author%}">
          <img class="w-50" src="{{tr.image.url}}">
        </a>
        </div>
        <div class = "col-md-4 text-left">
           <h2>{{tr.text}}</h2>
        </div>
    </div>
     {%endfor%}
{% endblock %}

templates/main/profile.html
{% extends "layout/basic.html" %}
{%block content%}
    <div class="container my-3">
      <div class="row">
         <div class = "col-md-4 text-left">
           <h2>{{user.username}}</h2>
           <p>Телефон:{{user.phone}}</p>
           <p>День рождения:{{user.bithrday}}</p>
           <p>О себе:{{user.bio}}</p>
           <p>Пол:{{user.gender}}</p>
           <a class="btn btn-primary" href="{% url 'main:profile_change' %}" role="button">Изменить данные</a>
            <a class="btn btn-primary" href="{% url 'main:profile_post_add' %}" role="button">Добавить пост</a>
        </div>
        <div class = "col-md-6">
          <a >
          <img class="w-100" src="{{user.avatar.url}}">
        </a>
        </div>
      </div>
       {%for tr in  posts%}
    <div class="container my-5">
      <div class="row">
        <div class = "col-md-8">
          <a href="{% url 'main:detail' post_pk=tr.id author=tr.author%}">
          <img class="w-50" src="{{tr.image.url}}">
        </a>
        </div>
        <div class = "col-md-4 text-left">
           <h2>{{tr.text}}</h2>
        </div>
    </div>
     {%endfor%}
{% endblock %}

templates/main/profile_post_add.html
{% extends "layout/basic.html" %}
{% load bootstrap5 %}
{%block content%}
    <b2>Добавление объявления</b2>
<form method="post" enctype="multipart/form-data" >
  {% csrf_token %}
  {{form.as_p}}
  {% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% endblock %}

templates/main/register_done.html
{% extends "layout/basic.html" %}
{%block content%}

<p>Регестрация завершина</p>
{% endblock %}

templates/main/register_user.html
{% extends "layout/basic.html" %}
{% load bootstrap5 %}
{%block content%}
 <form method="post" >
      {% csrf_token %}
       {% bootstrap_form form %}
      <button type="submit">Зарегистрироваться</button>
    </form>
{% endblock %}